import { useEffect, useState } from 'react';
import { Crown, Trophy, Download, ImageIcon } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import type { Winner } from '@/lib/types';
import { PageHeader } from '@/components/PageHeader';
import { Card } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { Loading, EmptyState } from '@/components/States';
import { formatDate, formatMoney } from '@/lib/utils';
import { useRouter } from '@/context/RouterContext';

const YOUTUBE_CHANNEL = 'https://www.youtube.com/@bgmiarena';

export function WinnersPage() {
  const { navigate } = useRouter();
  const [winners, setWinners] = useState<Winner[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      const { data } = await supabase
        .from('winners')
        .select('*, tournament:tournaments(*)')
        .order('created_at', { ascending: false });
      setWinners((data as Winner[]) || []);
      setLoading(false);
    })();
  }, []);

  const downloadResultSheet = (w: Winner) => {
    const lines = [
      'BGMI ARENA — RESULT SHEET',
      '==========================',
      `Tournament: ${w.tournament?.title || 'N/A'}`,
      `Winner Team: ${w.team_name}`,
      `Prize Amount: ${formatMoney(w.prize_amount)}`,
      `Match Date: ${formatDate(w.match_date)}`,
      '',
      'Match Statistics:',
      ...Object.entries(w.match_stats || {}).map(([k, v]) => `  ${k}: ${String(v)}`),
      '',
      'Generated by BGMI Arena',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `result-${w.team_name.replace(/\s+/g, '_')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div>
      <PageHeader title="Winner Gallery" subtitle="Every champion, every prize, every proof. Browse our hall of winners in chronological order." />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 py-10">
        {loading ? (
          <Loading />
        ) : winners.length === 0 ? (
          <EmptyState
            icon={<Crown size={40} />}
            title="No winners yet"
            message="Once tournaments complete, champions will be showcased here with screenshots and payment proofs."
          />
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {winners.map((w) => (
              <Card key={w.id} hover className="overflow-hidden group">
                {/* Winner screenshot */}
                <div className="relative h-48 overflow-hidden bg-bg-elevated">
                  {w.winner_screenshot_url ? (
                    <img src={w.winner_screenshot_url} alt={w.team_name} loading="lazy" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" />
                  ) : (
                    <div className="w-full h-full bg-gradient-to-br from-primary-500/20 to-accent-500/20 flex items-center justify-center">
                      <Crown size={48} className="text-primary-500/50" />
                    </div>
                  )}
                  <div className="absolute top-3 left-3">
                    <Badge tone="orange"><Crown size={12} /> Champion</Badge>
                  </div>
                </div>

                <div className="p-5 space-y-3">
                  <div className="flex items-center gap-3">
                    {w.team_logo_url ? (
                      <img src={w.team_logo_url} alt="" className="w-10 h-10 rounded-lg object-cover" />
                    ) : (
                      <div className="w-10 h-10 rounded-lg bg-bg-elevated flex items-center justify-center font-bold text-primary-400">
                        {w.team_name[0]}
                      </div>
                    )}
                    <div className="flex-1 min-w-0">
                      <h3 className="font-display font-bold text-white truncate">{w.team_name}</h3>
                      <p className="text-xs text-neutral-500 truncate">{w.tournament?.title || 'Tournament'}</p>
                    </div>
                  </div>

                  <div className="flex items-center justify-between text-sm">
                    <div>
                      <p className="text-xs text-neutral-500">Prize</p>
                      <p className="font-display font-bold text-primary-400">{formatMoney(w.prize_amount)}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-xs text-neutral-500">Date</p>
                      <p className="text-sm text-neutral-300">{formatDate(w.match_date)}</p>
                    </div>
                  </div>

                  {/* Match stats */}
                  {w.match_stats && Object.keys(w.match_stats).length > 0 && (
                    <div className="grid grid-cols-3 gap-2 pt-3 border-t border-border-subtle">
                      {Object.entries(w.match_stats).slice(0, 3).map(([k, v]) => (
                        <div key={k} className="text-center">
                          <p className="text-xs text-neutral-500 capitalize">{k}</p>
                          <p className="text-sm font-semibold text-neutral-200">{String(v)}</p>
                        </div>
                      ))}
                    </div>
                  )}

                  {/* Proofs */}
                  <div className="flex items-center gap-2 pt-3 border-t border-border-subtle">
                    {w.payment_screenshot_url && (
                      <a href={w.payment_screenshot_url} target="_blank" rel="noreferrer" className="flex-1">
                        <button className="w-full flex items-center justify-center gap-1.5 text-xs text-accent-400 hover:text-accent-300 transition-colors py-1.5 rounded bg-accent-500/10">
                          <ImageIcon size={12} /> Payment Proof
                        </button>
                      </a>
                    )}
                    <button
                      onClick={() => downloadResultSheet(w)}
                      className="flex-1 flex items-center justify-center gap-1.5 text-xs text-primary-400 hover:text-primary-300 transition-colors py-1.5 rounded bg-primary-500/10"
                    >
                      <Download size={12} /> Result Sheet
                    </button>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        )}

        {/* YouTube CTA */}
        <Card className="mt-10 p-6 flex flex-col sm:flex-row items-center justify-between gap-4 bg-gradient-to-r from-red-500/10 to-bg-card border border-red-500/20">
          <div className="flex items-center gap-3">
            <Trophy size={24} className="text-red-400" />
            <div>
              <h3 className="font-display font-bold text-white">Watch Winner Highlights</h3>
              <p className="text-sm text-neutral-400">Catch the best moments on our YouTube channel.</p>
            </div>
          </div>
          <a href={YOUTUBE_CHANNEL} target="_blank" rel="noreferrer">
            <Button variant="outline" className="border-red-500 text-red-400 hover:bg-red-500 hover:text-white">Watch Now</Button>
          </a>
        </Card>
      </div>
    </div>
  );
}
